"""empty message

Revision ID: ffdf28075
Revises: None
Create Date: 2014-02-08 22:21:29.317389

"""

# revision identifiers, used by Alembic.
revision = 'ffdf28075'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortName', sa.String(length=15), nullable=True),
    sa.Column('displayName', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortName', sa.String(length=15), nullable=True),
    sa.Column('displayName', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], )
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('homeGoalie', sa.Integer(), nullable=True),
    sa.Column('visitorGoalie', sa.Integer(), nullable=True),
    sa.Column('homeShooter', sa.Integer(), nullable=True),
    sa.Column('visitorShooter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['homeGoalie'], ['player.id'], ),
    sa.ForeignKeyConstraint(['homeShooter'], ['player.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.ForeignKeyConstraint(['visitorGoalie'], ['player.id'], ),
    sa.ForeignKeyConstraint(['visitorShooter'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('players')
    op.drop_table('league')
    op.drop_table('player')
    ### end Alembic commands ###
